# Generated by Django 5.0.6 on 2024-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='episode',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
