# Generated by Django 5.0.6 on 2024-10-04 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0007_episode_rating_episode_rating_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='subtitles/')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='vigi2.series')),
            ],
        ),
    ]
