# Generated by Django 5.0.6 on 2024-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0008_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
    ]
