# Generated by Django 5.0.6 on 2024-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0009_episode_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='category',
            field=models.CharField(choices=[('korean', 'Korean'), ('indian', 'Indian'), ('hollywood', 'Hollywood'), ('nollywood', 'Nollywood'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
