# Generated by Django 5.0.6 on 2024-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0010_episode_slug_series_slug_alter_series_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
