# Generated by Django 5.0.6 on 2024-11-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vigi2', '0011_series_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-13'),
            preserve_default=False,
        ),
    ]
